CREATE TABLE Clients
(
	[ClientID] INT NOT NULL PRIMARY KEY IDENTITY,
	[Login] NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[Address] NVARCHAR(500) NOT NULL,
)
